# Generated by Django 3.2.9 on 2021-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211121_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_mark',
            field=models.BooleanField(default=False, verbose_name='check mark'),
        ),
    ]
