# Generated by Django 3.2.9 on 2021-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_check_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoseries',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
