# Generated by Django 3.2.9 on 2021-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photoseries_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlephoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
