# Generated by Django 3.2.9 on 2021-11-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_singlephoto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoseries',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_series', to='api.collection'),
        ),
    ]
