# Generated by Django 3.2.9 on 2021-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_photoseries_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoseries',
            name='collection',
        ),
        migrations.AddField(
            model_name='photoseries',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collections_series', to='api.Collection'),
        ),
    ]
