# Generated by Django 3.2.9 on 2021-12-01 20:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211126_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlephoto',
            name='photo',
            field=models.ImageField(upload_to=api.models.SinglePhoto.get_image_path),
        ),
    ]
