# Generated by Django 3.2.9 on 2021-12-01 22:13

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_singlephoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(upload_to=api.models.Collection.get_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='singlephoto',
            name='photo',
            field=models.ImageField(upload_to=api.models.SinglePhoto.get_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.User.get_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif'])]),
        ),
    ]
