# Generated by Django 3.2.9 on 2021-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211202_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoseries',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
